"""Email completion notifications for scripts and cluster jobs.

A single ``--mail-me`` CLI flag with three modes::

    off    - No email sent.
    log    - Send email on completion (success or failure) with a log preview
             in the body and the full captured log attached.
    output - Same as ``log`` plus attach output files generated by the script
             (e.g. PNG, PDF, TEX).  Files larger than 25 MB are skipped.

Consumers customize the branding via :func:`mail_completion` /
:func:`format_mail_content` parameters (``subject_prefix``, ``footer_text``),
the captured logger name (:func:`setup_log_capture` ``logger_name``), and the
``.env`` location (``env_file``).  SMTP delivery, including the fallback DNS
resolver for flaky compute nodes, lives in :mod:`cluster_kit.email.smtp`.
"""

from __future__ import annotations

import argparse
import copy
import logging
import os
import tempfile
from io import StringIO
from pathlib import Path

from rich.console import Console
from rich.text import Text

from cluster_kit.email.smtp import (
    MAX_ATTACHMENT_BYTES,
    send_notification,
)

__all__ = [
    "add_mail_args",
    "should_mail",
    "setup_log_capture",
    "get_log_file_path",
    "get_log_preview",
    "teardown_log_capture",
    "capture_rich_output",
    "format_mail_content",
    "send_notification",
    "mail_completion",
    "MAX_ATTACHMENT_BYTES",
]


class _StripMarkupFormatter(logging.Formatter):
    """Strips Rich markup tags from log messages before writing to plain-text files."""

    def format(self, record: logging.LogRecord) -> str:
        record = copy.copy(record)
        try:
            msg = record.getMessage()
            record.msg = Text.from_markup(msg).plain
            record.args = ()
        except Exception:
            pass
        return super().format(record)


# ---------------------------------------------------------------------------
# CLI helpers
# ---------------------------------------------------------------------------


def add_mail_args(parser: argparse.ArgumentParser) -> None:
    """
    Add the ``--mail-me`` flag to *parser*.

    Usage inside a script::

        parser = argparse.ArgumentParser(...)
        add_mail_args(parser)
        args = parser.parse_args()
    """
    group = parser.add_argument_group("email notifications")
    group.add_argument(
        "--mail-me",
        type=str,
        choices=["off", "log", "output"],
        default="log",
        help=(
            "Email mode: off=none, log=email with log attached, "
            "output=log + script outputs attached (default: log)"
        ),
    )


def should_mail(args: argparse.Namespace) -> bool:
    """Return True if an email should be sent given *args*."""
    return getattr(args, "mail_me", "off") != "off"


# ---------------------------------------------------------------------------
# Log capture
# ---------------------------------------------------------------------------

_log_file_path: Path | None = None
_log_file_handler: logging.FileHandler | None = None
_log_capture_logger: logging.Logger | None = None


def setup_log_capture(logger_name: str = "") -> Path:
    """
    Add a ``FileHandler`` to *logger_name* that writes to a temp file.

    Call this **after** logging setup and ``parse_args()``, only when
    ``args.mail_me != "off"``.  The captured log is later attached to the
    email by :func:`mail_completion`.

    Returns the path to the temporary log file.

    .. note::
       Attach to the specific logger your application logs through, not the
       root logger, when that logger is configured with ``propagate = False``
       (otherwise its messages never reach root handlers, and nothing is
       captured).  ``logger_name=""`` targets the root logger.
    """
    global _log_file_path, _log_file_handler, _log_capture_logger

    # If already capturing, return existing path
    if _log_file_path is not None:
        return _log_file_path

    fd, path = tempfile.mkstemp(suffix=".txt", prefix="cluster_kit_")
    os.close(fd)
    _log_file_path = Path(path)

    _log_file_handler = logging.FileHandler(path, mode="w", encoding="utf-8")
    _log_file_handler.setLevel(logging.DEBUG)
    formatter = _StripMarkupFormatter(
        "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    _log_file_handler.setFormatter(formatter)
    _log_capture_logger = logging.getLogger(logger_name)
    _log_capture_logger.addHandler(_log_file_handler)

    return _log_file_path


def get_log_file_path() -> Path | None:
    """Return the path to the captured log file, or ``None``."""
    return _log_file_path


def get_log_preview(max_lines: int = 60) -> str:
    """
    Return the first *max_lines / 2* and last *max_lines / 2* lines of the
    captured log.  If the log is shorter than *max_lines*, return it in full.
    """
    if _log_file_path is None or not _log_file_path.exists():
        return "(no log captured)"

    lines = _log_file_path.read_text(encoding="utf-8", errors="replace").splitlines()
    if len(lines) <= max_lines:
        return "\n".join(lines)

    half = max_lines // 2
    head = lines[:half]
    tail = lines[-half:]
    omitted = len(lines) - max_lines
    return "\n".join(head + [f"\n... ({omitted} lines omitted) ...\n"] + tail)


def teardown_log_capture() -> None:
    """Remove the file handler, flushing and closing it (keeps the temp file)."""
    global _log_file_handler, _log_file_path, _log_capture_logger
    if _log_file_handler is not None:
        _log_file_handler.flush()  # Ensure all buffered logs are written to disk
        if _log_capture_logger is not None:
            _log_capture_logger.removeHandler(_log_file_handler)
        _log_file_handler.close()
        _log_file_handler = None
    _log_file_path = None
    _log_capture_logger = None


# ---------------------------------------------------------------------------
# Rich capture
# ---------------------------------------------------------------------------


def capture_rich_output(renderable: object) -> str:
    """
    Render a Rich object (Table, Panel, ...) to plain text.

    Useful for embedding the summary tables that scripts already produce into
    the email body.
    """
    buf = StringIO()
    temp_console = Console(file=buf, width=120, no_color=True, force_terminal=False)
    temp_console.print(renderable)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Email formatting
# ---------------------------------------------------------------------------


def _format_runtime(seconds: float) -> str:
    """Human-readable runtime string."""
    total = int(seconds)
    hours, remainder = divmod(total, 3600)
    minutes, secs = divmod(remainder, 60)
    if hours > 0:
        return f"{hours}h {minutes}m {secs}s"
    if minutes > 0:
        return f"{minutes}m {secs}s"
    return f"{secs}s"


def _filter_attachments(
    paths: list[Path | str],
) -> tuple[list[Path], list[str]]:
    """
    Filter *paths* by existence and size (``MAX_ATTACHMENT_BYTES``).

    Accepts both ``Path`` objects and plain strings (auto-converted).

    Returns ``(valid, skipped)`` where *skipped* contains human-readable
    reasons for each dropped file.
    """
    valid: list[Path] = []
    skipped: list[str] = []
    for p in paths:
        p = Path(p)
        if not p.exists():
            skipped.append(f"{p.name} (file not found)")
            continue
        size = p.stat().st_size
        if size > MAX_ATTACHMENT_BYTES:
            mb = size / 1_000_000
            skipped.append(f"{p.name} ({mb:.1f} MB > 25 MB limit)")
            continue
        valid.append(p)
    return valid, skipped


def format_mail_content(
    script_path: str,
    args: argparse.Namespace,
    status: str,
    runtime_seconds: float,
    summary_text: str = "",
    log_preview: str = "",
    attachment_names: list[str] | None = None,
    skipped_attachments: list[str] | None = None,
    subject_prefix: str = "[job] |",
    footer_text: str = "cluster-kit notification",
) -> tuple[str, str, str]:
    """
    Build email subject, HTML body, and plain-text body.

    Parameters
    ----------
    script_path : str
        ``__file__`` of the calling script.
    args : argparse.Namespace
        Parsed CLI arguments (``mail_me`` is excluded from the email).
    status : str
        ``"success"`` or ``"failure"``.
    runtime_seconds : float
        Wall-clock runtime of the script.
    summary_text : str
        Pre-rendered Rich output (plain text) to include in the email.
    log_preview : str
        Truncated log text for the email body.
    attachment_names : list[str] | None
        Names of files that will be attached (for listing in the body).
    skipped_attachments : list[str] | None
        Descriptions of attachments that were skipped (size limit, etc.).
    subject_prefix : str
        Leading token of the subject line (e.g. ``"[WSB] |"``).
    footer_text : str
        Footer label shown at the bottom of the email body.

    Returns
    -------
    tuple[str, str, str]
        ``(subject, html_body, plain_body)``
    """
    script_name = Path(script_path).stem
    runtime_str = _format_runtime(runtime_seconds)

    status_upper = status.upper()
    is_success = status == "success"
    status_color = "#28a745" if is_success else "#dc3545"
    status_label = "OK" if is_success else "FAIL"

    # ---- subject ----
    subject = f"{subject_prefix} {status_label} | {script_name} | {runtime_str}"

    # ---- arguments table rows ----
    skip_keys = {"mail_me"}
    args_dict = vars(args)
    args_rows_html = ""
    args_lines_plain: list[str] = []
    for key, value in sorted(args_dict.items()):
        if key in skip_keys or value is None:
            continue
        args_rows_html += (
            f"<tr>"
            f"<td style='padding:4px 12px;font-weight:bold;'>{key}</td>"
            f"<td style='padding:4px 12px;'>{value}</td>"
            f"</tr>\n"
        )
        args_lines_plain.append(f"  {key}: {value}")

    # ---- escape helpers ----
    def _esc(text: str) -> str:
        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    summary_escaped = _esc(summary_text)
    log_preview_escaped = _esc(log_preview)

    # ---- HTML sections ----
    args_section = ""
    if args_rows_html:
        args_section = (
            "<h3 style='margin:16px 0 8px;'>Arguments</h3>"
            "<table style='border-collapse:collapse;width:100%;margin-bottom:16px;'>"
            f"{args_rows_html}</table>"
        )

    summary_section = ""
    if summary_text:
        summary_section = (
            "<h3 style='margin:16px 0 8px;'>Output Summary</h3>"
            "<pre style='background:#f6f8fa;padding:16px;border-radius:6px;"
            "overflow-x:auto;font-size:13px;line-height:1.5;'>"
            f"{summary_escaped}</pre>"
        )

    log_section = ""
    if log_preview:
        log_section = (
            "<h3 style='margin:16px 0 8px;'>Log Preview</h3>"
            "<pre style='background:#f0f0f0;padding:16px;border-radius:6px;"
            "overflow-x:auto;font-size:12px;line-height:1.4;color:#333;'>"
            f"{log_preview_escaped}</pre>"
            "<p style='font-size:12px;color:#6a737d;'>"
            "Full log attached.</p>"
        )

    attachments_section = ""
    att_lines: list[str] = []
    if attachment_names:
        att_lines.append("<h3 style='margin:16px 0 8px;'>Attachments</h3><ul>")
        for name in attachment_names:
            att_lines.append(f"<li><code>{_esc(name)}</code></li>")
        att_lines.append("</ul>")
    if skipped_attachments:
        att_lines.append(
            "<p style='color:#856404;font-size:13px;'>"
            "<strong>Skipped attachments:</strong></p><ul>"
        )
        for reason in skipped_attachments:
            att_lines.append(f"<li style='color:#856404;'>{_esc(reason)}</li>")
        att_lines.append("</ul>")
    if att_lines:
        attachments_section = "\n".join(att_lines)

    # ---- HTML body ----
    html_body = (
        "<html><body style=\"font-family:'Courier New',monospace;"
        'background:#f6f8fa;padding:20px;">'
        "<div style='max-width:700px;margin:0 auto;background:white;"
        "border-radius:8px;border:1px solid #e1e4e8;overflow:hidden;'>"
        # Header
        f"<div style='background:{status_color};padding:16px 24px;color:white;'>"
        f"<h2 style='margin:0;'>{script_name} &mdash; {status_upper}</h2>"
        "</div>"
        # Body
        "<div style='padding:24px;'>"
        "<table style='border-collapse:collapse;width:100%;margin-bottom:16px;'>"
        "<tr style='border-bottom:1px solid #e1e4e8;'>"
        "<td style='padding:8px 12px;font-weight:bold;'>Script</td>"
        f"<td style='padding:8px 12px;'>{script_path}</td></tr>"
        "<tr style='border-bottom:1px solid #e1e4e8;'>"
        "<td style='padding:8px 12px;font-weight:bold;'>Status</td>"
        f"<td style='padding:8px 12px;color:{status_color};font-weight:bold;'>"
        f"{status_upper}</td></tr>"
        "<tr style='border-bottom:1px solid #e1e4e8;'>"
        "<td style='padding:8px 12px;font-weight:bold;'>Runtime</td>"
        f"<td style='padding:8px 12px;'>{runtime_str}</td></tr>"
        "</table>"
        f"{args_section}"
        f"{summary_section}"
        f"{log_section}"
        f"{attachments_section}"
        "</div>"
        # Footer
        "<div style='padding:12px 24px;background:#f6f8fa;"
        "border-top:1px solid #e1e4e8;font-size:12px;color:#6a737d;'>"
        f"{footer_text}"
        "</div></div></body></html>"
    )

    # ---- plain-text body ----
    args_block = "\n".join(args_lines_plain) if args_lines_plain else "  (none)"
    summary_block = f"\nOutput Summary:\n{summary_text}" if summary_text else ""
    log_block = f"\nLog Preview:\n{log_preview}" if log_preview else ""

    att_block = ""
    if attachment_names:
        att_block += "\nAttachments:\n" + "\n".join(
            f"  - {n}" for n in attachment_names
        )
    if skipped_attachments:
        att_block += "\nSkipped attachments:\n" + "\n".join(
            f"  - {r}" for r in skipped_attachments
        )

    plain_body = (
        f"{script_name} -- {status_upper}\n"
        f"{'=' * 40}\n"
        f"Script:  {script_path}\n"
        f"Status:  {status_upper}\n"
        f"Runtime: {runtime_str}\n\n"
        f"Arguments:\n{args_block}"
        f"{summary_block}"
        f"{log_block}"
        f"{att_block}\n"
    )

    return subject, html_body, plain_body


# ---------------------------------------------------------------------------
# Convenience wrapper (the function scripts actually call)
# ---------------------------------------------------------------------------


def mail_completion(
    script_path: str,
    args: argparse.Namespace,
    succeeded: bool,
    runtime_seconds: float,
    summary_text: str = "",
    output_files: list[Path | str] | None = None,
    error_message: str = "",
    subject_prefix: str = "[job] |",
    footer_text: str = "cluster-kit notification",
    env_file: Path | None = None,
) -> bool:
    """
    One-call convenience: decide whether to send, format, and dispatch.

    Typical usage at the end of ``main()``::

        mail_completion(
            __file__, args, succeeded=True,
            runtime_seconds=elapsed,
            summary_text=capture_rich_output(summary_table),
        )

    Parameters
    ----------
    script_path : str
        ``__file__`` of the calling script.
    args : argparse.Namespace
        Parsed CLI arguments (must include ``mail_me`` attribute added by
        :func:`add_mail_args`).
    succeeded : bool
        Whether the script completed successfully.
    runtime_seconds : float
        Wall-clock runtime in seconds.
    summary_text : str
        Pre-rendered Rich output to embed in the email body.
    output_files : list[Path] | None
        Files to attach when ``--mail-me output`` is used (PNG, PDF, etc.).
        Ignored when mode is ``log`` or ``off``.
    error_message : str
        If the script failed, the error description to prepend to the summary.
    subject_prefix : str
        Leading token of the subject line.
    footer_text : str
        Footer label shown at the bottom of the email body.
    env_file : Path | None
        Explicit ``.env`` path to load config from (defaults to ``.env`` in cwd).

    Returns
    -------
    bool
        ``True`` if the email was sent, ``False`` otherwise.
    """
    mail_mode = getattr(args, "mail_me", "off")
    if mail_mode == "off":
        teardown_log_capture()
        return False

    status = "success" if succeeded else "failure"
    full_summary = summary_text
    if not succeeded and error_message:
        full_summary = f"ERROR: {error_message}\n\n{summary_text}"

    # ---- Flush log capture to ensure all buffered logs are written ----
    if _log_file_handler is not None:
        _log_file_handler.flush()

    # ---- Collect log preview ----
    log_preview = get_log_preview()

    # ---- Build attachment list ----
    all_attachments: list[Path] = []
    attachment_names: list[str] = []
    skipped: list[str] = []

    # Always attach the log file
    log_path = get_log_file_path()
    if log_path is not None and log_path.exists():
        all_attachments.append(log_path)
        attachment_names.append(log_path.name)

    # In "output" mode, also attach output files
    if mail_mode == "output" and output_files:
        valid, skip_reasons = _filter_attachments(output_files)
        all_attachments.extend(valid)
        attachment_names.extend(p.name for p in valid)
        skipped.extend(skip_reasons)

    # ---- Tear down log capture before sending ----
    teardown_log_capture()

    # ---- Format and send ----
    subject, html_body, plain_body = format_mail_content(
        script_path,
        args,
        status,
        runtime_seconds,
        full_summary,
        log_preview=log_preview,
        attachment_names=attachment_names,
        skipped_attachments=skipped if skipped else None,
        subject_prefix=subject_prefix,
        footer_text=footer_text,
    )
    return send_notification(
        subject, html_body, plain_body, all_attachments, env_file=env_file
    )
